version: '3.9'

services:
  app:
    build: . 
    container_name: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env 

  db: 
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env 
    volumes:
      - dbb:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbb: 