# Generated by Django 4.1.3 on 2022-11-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('tipo', models.CharField(choices=[('F', 'Fisica'), ('J', 'Juridica')], max_length=1)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dt_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de alteração')),
            ],
        ),
    ]
